# Generated by Django 4.0.6 on 2022-07-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.ImageField(default='portrait/model-1.png', upload_to='projects/'),
            preserve_default=False,
        ),
    ]
