# Generated by Django 4.0.6 on 2022-07-24 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_project_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='discord',
        ),
        migrations.RemoveField(
            model_name='home',
            name='img',
        ),
        migrations.RemoveField(
            model_name='home',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='home',
            name='youtube',
        ),
        migrations.RemoveField(
            model_name='project',
            name='show_on_page',
        ),
    ]
